Isdb 548 case reference screen
hmcts/fis-ds-update-web pull request #68
Opened 2023-02-06 16:25 UTC by hmcts-abduldaim

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-02-13 18:03 UTC, yogendraU requested changes

2023-02-14 10:44 UTC, hmcts-abduldaim commented on src/main/app/case/C100CaseApi.ts
> +    document_hash: string;
It wasn't added by me. it was already added prior to time when I have received the ticket.

2023-02-14 10:44 UTC, hmcts-abduldaim commented on src/main/app/controller/AppRequest.ts
> +    C100Api: any;
It wasn't added by me. it was already added prior to time when I have received the ticket.

2023-02-14 10:48 UTC, hmcts-abduldaim commented on src/main/app/controller/GetController.ts
> +      console.log({ msg: 'triggering data disclosure as none' });
Used successfully

2023-02-14 10:52 UTC, hmcts-abduldaim commented on src/main/app/form/validation.ts
> +export type Validator = (
cleaned

2023-02-14 10:56 UTC, hmcts-abduldaim commented on src/main/app/s2s/rpeAuth.ts
> +        microservice: 'fis_ds_update_web',
resolved

2023-02-14 10:59 UTC, hmcts-abduldaim commented on src/main/modules/fileupload/index.ts
> +    // const DefaultFileUploadSize = config.get<number>('documentManagement.uploadSizeinMB');
resolved

2023-02-14 11:01 UTC, hmcts-abduldaim commented on src/main/steps/edgecase/casefinder/content.test.ts
> +        "Some of the information yo have given doesn't match our records. Please enter the right value and retry - welsh",
resolved

2023-02-14 11:01 UTC, hmcts-abduldaim commented on src/main/steps/edgecase/casefinder/content.ts
> +        "Some of the information yo have given doesn't match our records. Please enter the right value and retry",
resolved

2023-02-14 11:01 UTC, hmcts-abduldaim commented on src/main/steps/edgecase/casefinder/postController.ts
> +    const baseURL = `http://localhost:3100/case/dss-orchestration/${req.body.applicantCaseId}`;
the main api will pulled for config.

2023-02-14 11:04 UTC, hmcts-abduldaim commented on src/main/steps/edgecase/casefinder/template.njk
> +{% set formInputError = ''%}
I guess we discussed the solution before implementing it

2023-02-14 11:04 UTC, hmcts-abduldaim commented on src/main/steps/edgecase/citizen-data-verification/content.ts
> +  } else {
they both are different one is taking argument

2023-02-14 11:05 UTC, hmcts-abduldaim commented on src/main/app/fileUpload/documentManager.ts
> +    httpsAgent: new https.Agent({ rejectUnauthorized: false }),
ok

2023-02-22 12:10 UTC, yogendraU approved these changes

2023-02-22 12:22 UTC, rahulsanjava19 approved these changes

2023-02-22 12:26 UTC, merged